export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_DATA = 'SET_USER_DATA';

export const ADD_AVAILABLE_GAME = 'ADD_AVAILABLE_GAME';
export const REMOVE_AVAILABLE_GAME = 'REMOVE_AVAILABLE_GAME';
export const EMPTY_AVAILABLE_GAMES = 'EMPTY_AVAILABLE_GAMES';
export const MARK_SET = 'MARK_SET';

export const SET_TASK_MANAGER_DATA = 'SET_TASK_MANAGER_DATA';
export const SET_TASK_MANAGER_ERROR = 'SET_TASK_MANAGER_ERROR';
